services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: oop-php-right-way-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:alpine
    container_name: oop-php-right-way-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
